export const SIGNIN = 'SIGNIN';
export const AUTHENTICATED = 'AUTHENTICATED';
export const AUTHENTICATED_USER = 'AUTHENTICATED_USER';
export const ERROR_OCCURRED = 'ERROR_OCCURRED';
export const OTPVERIFY = 'OTPVERIFY';
export const SIGNOUT = 'SIGNOUT';
